const initialOrders = [
  {
    id: 1,
    customer: "Ahmed Ali",
    email: "ahmed@example.com",
    phone: "+20 100 555 1234",
    address: "Nasr City, Cairo",
    products: [{ name: "iPhone 15 Pro", qty: 1 }],
    warehouse: "Main Warehouse",
    shippingCompany: "DHL Express",
    status: "processing",
    total: 1200,
    createdAt: "2026-04-25",
  },

  {
    id: 2,
    customer: "Sara Mohamed",
    email: "sara@example.com",
    phone: "+20 111 222 3333",
    address: "Miami, Alexandria",
    products: [{ name: "Samsung TV 55 inch", qty: 1 }],
    warehouse: "Cairo Warehouse",
    shippingCompany: "Aramex",
    status: "shipped",
    total: 800,
    createdAt: "2026-04-24",
  },

  {
    id: 3,
    customer: "Omar Hassan",
    email: "omar@example.com",
    phone: "+20 122 444 8888",
    address: "6th of October, Giza",
    products: [
      { name: "Air Fryer XL", qty: 1 },
      { name: "Blender Kitchen Pro", qty: 1 },
    ],
    warehouse: "Cairo Warehouse",
    shippingCompany: "Egypt Post",
    status: "delivered",
    total: 225,
    createdAt: "2026-04-22",
  },

  {
    id: 4,
    customer: "Mohamed Farid",
    email: "farid@example.com",
    phone: "+20 155 999 1111",
    address: "Damietta City",
    products: [{ name: "MacBook Pro M3", qty: 1 }],
    warehouse: "Main Warehouse",
    shippingCompany: "DHL Express",
    status: "processing",
    total: 2200,
    createdAt: "2026-04-26",
  },

  {
    id: 5,
    customer: "Youssef Adel",
    email: "youssef@example.com",
    phone: "+20 199 777 2222",
    address: "Mansoura",
    products: [{ name: "Sony Headphones WH-1000XM5", qty: 1 }],
    warehouse: "Main Warehouse",
    shippingCompany: "Aramex",
    status: "cancelled",
    total: 400,
    createdAt: "2026-04-20",
  },

  {
    id: 6,
    customer: "Hassan Ibrahim",
    email: "hassan@example.com",
    phone: "+20 101 333 7777",
    address: "Tanta",
    products: [{ name: "Adidas Hoodie", qty: 2 }],
    warehouse: "Alex Warehouse",
    shippingCompany: "Egypt Post",
    status: "shipped",
    total: 180,
    createdAt: "2026-04-23",
  },

  {
    id: 7,
    customer: "Khaled Saad",
    email: "khaled@example.com",
    phone: "+20 110 888 9999",
    address: "Damietta",
    products: [{ name: "Gaming Chair Pro", qty: 1 }],
    warehouse: "Alex Warehouse",
    shippingCompany: "DHL Express",
    status: "processing",
    total: 350,
    createdAt: "2026-04-27",
  },
];

export default initialOrders;
