const initialShippingCompanies = [
  // 🇪🇺 Europe
  {
    id: 1,
    name: "DHL Express",
    email: "info@dhl.com",
    country: "Germany",
    region: "Europe",
    type: "International",
    phone: "+49 228 1820",
    status: "active",
  },
  {
    id: 2,
    name: "DPD Group",
    email: "support@dpd.com",
    country: "France",
    region: "Europe",
    type: "International",
    phone: "+33 1 58 88 88 88",
    status: "active",
  },
  {
    id: 3,
    name: "GLS",
    email: "info@gls-group.com",
    country: "Netherlands",
    region: "Europe",
    type: "International",
    phone: "+31 20 520 0800",
    status: "active",
  },

  // 🌍 Gulf (Middle East)
  {
    id: 4,
    name: "Aramex",
    email: "support@aramex.com",
    country: "UAE",
    region: "Gulf",
    type: "Regional",
    phone: "+971 600 544000",
    status: "active",
  },
  {
    id: 5,
    name: "SMSA Express",
    email: "support@smsaexpress.com",
    country: "Saudi Arabia",
    region: "Gulf",
    type: "Regional",
    phone: "+966 9200 00999",
    status: "active",
  },
  {
    id: 6,
    name: "Qatar Post",
    email: "info@qpost.com.qa",
    country: "Qatar",
    region: "Gulf",
    type: "Local",
    phone: "+974 4446 4000",
    status: "active",
  },

  // 🌍 Africa
  {
    id: 7,
    name: "Egypt Post",
    email: "support@egyptpost.gov.eg",
    country: "Egypt",
    region: "Africa",
    type: "Local",
    phone: "16789",
    status: "active",
  },
  {
    id: 8,
    name: "Bosta",
    email: "support@bosta.co",
    country: "Egypt",
    region: "Africa",
    type: "Local",
    phone: "0224567890",
    status: "active",
  },
  {
    id: 9,
    name: "PostNet",
    email: "info@postnet.co.za",
    country: "South Africa",
    region: "Africa",
    type: "Regional",
    phone: "+27 11 345 1300",
    status: "active",
  },
  {
    id: 10,
    name: "Sendy Logistics",
    email: "support@sendyit.com",
    country: "Kenya",
    region: "Africa",
    type: "Regional",
    phone: "+254 709 725 000",
    status: "active",
  },
];

export default initialShippingCompanies;
