const suppliers = [
  {
    id: 1,
    name: "Local Trading Co.",
    type: "local",
    email: "contact@localtrading.com",
    phone: "+20 100 123 4567",
    country: "Egypt",
    status: "active",
    rating: 4.5,
    supplies: ["Electronics", "Home & Kitchen"],
  },
  {
    id: 2,
    name: "Global Importers Ltd.",
    type: "foreign",
    email: "info@globalimporters.com",
    phone: "+44 20 7946 0958",
    country: "United Kingdom",
    status: "active",
    rating: 4.8,
    supplies: ["Electronics", "Fashion"],
  },
  {
    id: 3,
    name: "Asia Supply Hub",
    type: "foreign",
    email: "sales@asiasupply.com",
    phone: "+86 10 8888 9999",
    country: "China",
    status: "inactive",
    rating: 3.9,
    supplies: ["Electronics", "Home & Kitchen"],
  },
  {
    id: 4,
    name: "Delta Market Supplies",
    type: "local",
    email: "delta@supplies.com",
    phone: "+20 111 222 3333",
    country: "Egypt",
    status: "active",
    rating: 4.2,
    supplies: ["Food & Beverages", "Home & Kitchen"],
  },
  {
    id: 5,
    name: "Euro Wholesale Group",
    type: "foreign",
    email: "info@eurogroup.com",
    phone: "+49 30 123456",
    country: "Germany",
    status: "active",
    rating: 4.6,
    supplies: ["Fashion", "Electronics"],
  },
  {
    id: 6,
    name: "Nile Valley Suppliers",
    type: "local",
    email: "nile@egyptsup.com",
    phone: "+20 122 555 8888",
    country: "Egypt",
    status: "active",
    rating: 4.0,
    supplies: ["Food & Beverages"],
  },
  {
    id: 7,
    name: "American Trade Partners",
    type: "foreign",
    email: "support@atp.com",
    phone: "+1 212 555 0100",
    country: "USA",
    status: "active",
    rating: 4.7,
    supplies: ["Electronics", "Fashion"],
  },
  {
    id: 8,
    name: "Red Sea Logistics",
    type: "local",
    email: "redsea@logistics.com",
    phone: "+20 100 999 7777",
    country: "Egypt",
    status: "inactive",
    rating: 3.8,
    supplies: ["Home & Kitchen", "Electronics"],
  },
  {
    id: 9,
    name: "Tokyo Supply Chain",
    type: "foreign",
    email: "tokyo@supply.jp",
    phone: "+81 3 1234 5678",
    country: "Japan",
    status: "active",
    rating: 4.9,
    supplies: ["Electronics"],
  },
  {
    id: 10,
    name: "Mena Wholesale Network",
    type: "local",
    email: "mena@wholesale.com",
    phone: "+20 155 666 7777",
    country: "Egypt",
    status: "active",
    rating: 4.3,
    supplies: ["Fashion", "Food & Beverages"],
  },

  // 🔥 موردين إضافيين (زيادة احترافية)
  {
    id: 11,
    name: "Smart Tech Supplies",
    type: "foreign",
    email: "smart@tech.com",
    phone: "+82 10 2222 3333",
    country: "South Korea",
    status: "active",
    rating: 4.6,
    supplies: ["Electronics"],
  },
  {
    id: 12,
    name: "Cairo Wholesale Center",
    type: "local",
    email: "cairo@wholesale.com",
    phone: "+20 101 888 7777",
    country: "Egypt",
    status: "active",
    rating: 4.1,
    supplies: ["Fashion", "Home & Kitchen", "Food & Beverages"],
  },
];

export default suppliers;
