const products = [
  {
    id: 1,
    name: "iPhone 15 Pro",
    category: "Electronics",
    price: 1200,
    status: "active",
    supplierId: 2,
  },
  {
    id: 2,
    name: "Samsung TV 55 inch",
    category: "Electronics",
    price: 800,
    status: "active",
    supplierId: 3,
  },
  {
    id: 3,
    name: "Nike Air Force",
    category: "Fashion",
    price: 120,
    status: "inactive",
    supplierId: 5,
  },
  {
    id: 4,
    name: "MacBook Pro M3",
    category: "Electronics",
    price: 2200,
    status: "active",
    supplierId: 7,
  },
  {
    id: 5,
    name: "Air Fryer XL",
    category: "Home & Kitchen",
    price: 150,
    status: "active",
    supplierId: 4,
  },
  {
    id: 6,
    name: "Sony Headphones WH-1000XM5",
    category: "Electronics",
    price: 400,
    status: "active",
    supplierId: 11,
  },
  {
    id: 7,
    name: "Adidas Hoodie",
    category: "Fashion",
    price: 90,
    status: "active",
    supplierId: 10,
  },
  {
    id: 8,
    name: "Blender Kitchen Pro",
    category: "Home & Kitchen",
    price: 75,
    status: "active",
    supplierId: 6,
  },
  {
    id: 9,
    name: "Coffee Machine Deluxe",
    category: "Home & Kitchen",
    price: 200,
    status: "active",
    supplierId: 5,
  },
  {
    id: 10,
    name: "Gaming Chair Pro",
    category: "Electronics",
    price: 350,
    status: "inactive",
    supplierId: 8,
  },
];

export default products;
